name: test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          repository: Codeschool-Dart-Test/basic_math_function_test
          path: test
      - uses: dart-lang/setup-dart@v1.3
      - run: dart pub get
      - run: dart test
